package com.owr.so.commons;

public enum ScanEvent {

	DONE_SUCCESS, VALIDATION_MOUNTED_DISC, VALIDATION_OTHER_PCS_REPO,
	VALIDATION_BLANK_PATH, VALIDATION_NOT_A_REPO_FILE, VALIDATION_REPO_FILE_NOT_EXIST, DONE_FAIL,
	SCAN_NEW_DIR, SCAN_NEW_DIR_SKIPING, SCAN_FAILED, SCAN_FILE_OK_NEW, SCAN_FILE_SKIPPED, SCAN_FILE_OK_OLD,
}
